export const hebrew={
    'Username':'שם משתמש',
    'Password':'סיסמה',
    'Submit':'כניסה', 
    'Sign in':'כניסת משתמש', 
    'Log In':'דף כניסה', 
    'Log Out':'יציאה',
    'Customers':'לקוחות/אנשי קשר',
    'Products':'מוצרים',
    'Quotations':'הצעות מחיר',
    'Create Quotation':'צור הצעת מחיר',
    'Orders':'הזמנות',
    'Orders In Progress':'הפקות בחוץ',
    'Executed Orders':'הפקות שחזרו',
    'Statements':'דוחות',
    'Customer Data':'נתוני לקוח',
    'Customers Table':'טבלת לקוחות',
    'Products Table':'טבלת מוצרים',
    'Quotations Table':'טבלת הוצעות מחיר',
    'Student Production':'הפקת סטודנטים',
    'Camera Man':'צלמים',
    'Production Company':'חברת הפקה',
    'Lighting':'תאורנים',
    'Grip':'גריפ',
    'Sound':'סאונד',
    'Duplicate Name':'שם כבר קיים',
    'Duplicate SKU':'מק"ט כבר קיים',
    'History Table':'טבלת היסטוריה',
    'Assistant Producer':'ע. הפקה',
    'Supplier':'ספק',
    'Phone':'טלפון',
    'Cancel':'בטל',
    'Address':'כתובת',
    'Add New Product':'הוספת מוצר חדש',
    'Add New Quotation':'הוספת הוצעת מחיר חדשה',
    'Add New Child Product':'הוספת מוצר ילד חדש',
    'Terms of Payment':'תנאי תשלום',
    'City':'עיר',
    'ZIP':'מיקוד',
    'Search':'חיפוש',
    'Actions':'פעולות',
    'Save':'שמור',
    'Edit':'ערוך',
    'View':'צפה',
    'Back':'חזור',
    'Camera':'מלצמה',
    'Delete This Product':'למחוק מוצר זה',
    "And It's Children?":'יחד אם כל הילדים?',
    'Delete':'מחק',
    'Comments':'הערות',
    'Position':'תפקיד',
    'Upload Date':'תאריך',
    'Immediate':'מיידי',
    'Credit 30':'שוטף 30',
    'Credit 60':'שוטף 60',
    'Credit 90':'שוטף 90',
    'Add New':'הוספת',
    'Add New Customer':'הוספת לקוח חדש',
    'Edit Customer':'עריכת לקוח',
    'Customer':'לקוח',
    'Future Orders':'הזמנות עתידיות',
    'Add New Contact':'הוספת איש קשר',
    'Contacts':'אנשי קשר בחברה',
    'Country':'מדינה',
    'Child Added Successfuly,':'מוצר ילד הוסף בהצלחה',
    'Add Another Child?':'להוסיף מוצר ילד חדש?',
    'Documents':'מסמכים',
    'Pictures':'תמונות',
    'Status':'סטטוס',
    'Quotation For':'לכבוד',
    '#Order':'מס׳ הזמנה',
    '#Quotation':'מס׳ הצעת מחיר',
    'Units in Stock':'כמות במלאי',
    'Units Available':'כמות זמינה',
    'Product Name':'שם מוצר',
    'Total Price':'סה"כ מחיר',
    'Total Payment':'סה״כ לתשלום',
    'Special Discount':'הנחה מיוחדת',
    'No Discount Products': 'מוצר ללא הנחה ',
    'Total Payment - VAT':'סה״כ לתשלום לא כולל מע״מ',
    'Price':'מחיר',
    'Purchasing Price':'מחיר רכישה',
    'Purchasing Date':'תאריך רכישה',
    'Insurance Expiration Date':'תאריך סיום אחריות',
    'Amount':'כמות',
    'Item':'מוצר',
    'Name':'שם',
    'Add Related Item':'הוספת מוצר נלווה',
    'Add Related Accessorie':'הוספת אביזר נלווה',
    'From':'מתאריך',
    'Serial Number':'מספר סידורי',
    'Related Parent Products':'מוצרי אבא נלווים',
    'Related Accessories':'אביזרים נלווים',
    'Product Description':'תיאור מוצר',
    'Edit Parent Product':'עריכת מוצר אבא',
    'View Parent Product':'תצוגת מוצר אבא',
    'Edit Child Product':'עריכת מוצר ילד',
    'View Child Product':'תצוגת מוצר ילד',
    'Due Date':'תאריך יעד',
    'SKU':'מק"ט',
    'Dates':'תאריכים',
    'Total':'סה״כ',
    'Producer Name':'שם מפיק בפועל',
    'Producer Email':'דוא״ל מפיק',
    'Producer':'מפיק',
    'Department':'מחלקה',
    'Days':'ימים',
    'Price After Discount':'מחיר ליחידה לאחר הנחה',
    'Discount(%)':'(%)הנחה ליחידה',
    'Total Days':'סה"כ ימים',
    'Bar Code':'ברקוד',
    'To':'עד תאריך',
    'Project Name':'שם פרויקט',
    'Email':'דוא"ל',
    'ID':'ח.פ/ע.מ',
    'Customer Category':'קטגוריית לקוח',
    'Categories':'קטגוריות',
    'Category':'קטגוריה',
    'Entries Limit':'כמות להצגה',
    'Full Name':'שם מלא',
    'Add Child Product':'הוספת מוצר ילד',
    'Light':'תאורה',
    'Gaif':'גאיף',
    'Production':'הפקה',
    'Camp':'מחנה',
 	'Tripod + Stabilizers':'חצובה + מייצבים',
 	'Media':'מדיה',
 	'Success':'הצלחה',
 	'No Customer Selected':'לא נבחר לקוח',
 	'No Date Selected':'לא נבחר תאריך',
 	'Server Error':'שגיעת סרבר',
   'Power/Batteries':'כוח/סוללות',
 	'Lenses':'עדשות',
 	'Monitors':'מוניטורים',
 	'Box Set + Filters':'סט בוקס + פילטרים',
 	'Camera Equipment Accessories':'אביזירים לציוד מצלמה',
 	'Wireless Camera':'אלחוטי למצלמה',
 	'Flashlights 5600':'פנסים 5600',
 	'Flashlights 3200':'פנסים 3200',
 	'Kino Flashlight':'פנסי קינו',
 	'LED Flashlight/Special Flashlight':'פנסי לאד / פנס מיוחד',
 	'Stends':'סטנדים',
 	'Flags and Frames':'דגלים וסגרות',
   'Electrical Power' :'חשמל',
 	'Lighting Fixtures & Grips':'אבזרי תאורה וגריפ',
 	'Other Lighting':'תאורה אחר',
 	'DOLLY and Products':'דולי ומוצרים',
 	'Gabe and Products':'גייב ומוצרים',
 	'Grip Accessories':'אבזרי גריפ',
 	'Mixer and Recording Equipment':'מיקסר וציוד הקלטה',
 	'Sound Systems':'מערכות סאונד',
 	'Wireless':'אלחוטיות',
 	'Microphones and Accessories':'מיקרופונים ואבזרי',
 	'Other Sound':'אחר סאונד',
 	'Camp Equipment':'ציוד מחנה',
   'Generator + Vehicles':'גנרטור + רכבים',
   'in use' : 'לא פנוי',
   'Avilable' : 'פנוי',
   'parentType': 'סוג מוצר',
   'basic': 'בסיסי',
   'generic':'גנרי',
   'set':'סט',
   'Raw materials and consumables':'חומרי גלם וציוד מתכלה',
   'User logout in': 'יציאה מהמערכת בתוך'
}